### ISSUE TITLE
Is there a way for validation spec files which are using as a part of OAS3?

### ISSUE THREAD

**Issue by mbraint** [42Crunch/intellij-openapi-editor#16]
When I split OAS3 into multiple small files I want to have support autocompletion and validation over them.
For example it doesn't work for a file like that and potentially leads to errors.
```yaml
# schemas/Pet.yaml


type: object
required:
  - id
  - name
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  tag:
    type: string
```

If there is no such ability in current version it would be great to have it in nearest versions.

In my mind there are 2 variants how it would be implemented:
### 1. Via Comment Line
In each file which presents part of OAS3 to add some notation into the first comment line
with the part of specification that plugin will be use for validation and autocompletion

```yaml
# schemas/Pet.yaml

# schema: 'http://json-schema.org/draft-04/schema#definitions/Schema'
type: object
required:
  - id
  - name
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  tag:
    type: string
```

### 2. Recognize automatically

When some file mentioned in the main specification file through $ref
apply for that file validation rules and autocompletion automatically 

```yaml
# openapi.yaml

openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Multi-file boilerplate for OpenAPI Specification.
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets/{petId}:
    '200':
      content:
        application/json:
          schema:
            $ref: "./schemas/Pet.yaml"
```
